{
 "title": "Gitlab Runner monitoring",
 "description": "For the girlab runners exposed metrics (Autoscaling)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "runner",
    "query": "label_values(ci_runner_errors, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Runner Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_runner_version_info" }
   ]
  },
  {
   "title": "Concurrency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_runner_concurrent", "legendFormat": "{{job}} {{runner}}" }
   ]
  },
  {
   "title": "Runners limits",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    { "expr": "gitlab_runner_limit" }
   ]
  },
  {
   "title": "Errors Total N",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_runner_errors_total[1m])",
     "legendFormat": "{{runner}} {{level}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "API Request Statuses Total N",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_runner_api_request_statuses_total[1m])",
     "legendFormat": "{{job}} {{runner}}"
    }
   ]
  },
  {
   "title": "Autoscaling Machine States",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_autoscaling_machine_states",
     "legendFormat": "{{job}} {{state}}"
    }
   ]
  },
  {
   "title": "Request Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_request_concurrency",
     "legendFormat": "{{job}} {{runner}}"
    }
   ]
  },
  {
   "title": "Autoscaling Machine Creation Duration in Seconds (sum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_runner_autoscaling_machine_creation_duration_seconds_sum[1m]) / increase(gitlab_runner_autoscaling_machine_creation_duration_seconds_count[1m])",
     "legendFormat": "{{job}} {{executor}}"
    }
   ]
  },
  {
   "title": "Concurrency Exceeded Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_runner_request_concurrency_exceeded_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}