{
 "title": "Oracle",
 "description": "Grafana for oracle database monitor.",
 "tags": [ "oracledb" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(oracledb_exporter_oracle_up, instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1s,5s,10s,30s,1m,3m,5m,30m,1h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Widgets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "oracle status",
     "type": "singlestat",
     "description": "Views for database  Up or Down",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "oracledb_exporter_oracle_up{instance=\"$host\"}",
       "legendFormat": "oracleUP"
      }
     ]
    },
    {
     "title": "sessions",
     "type": "grafana-piechart-panel",
     "description": "Views for database session counts(active and inactive user or background sessions)",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "oracledb_session_total_sessions{instance=\"$host\",session_type=\"USER\",status=\"ACTIVE\"}",
       "legendFormat": "active_user_session"
      },
      {
       "expr": "oracledb_session_total_sessions{instance=\"$host\",session_type=\"USER\",status=\"INACTIVE\"}",
       "legendFormat": "inactive_user_session"
      },
      {
       "expr": "oracledb_session_total_sessions{instance=\"$host\",session_type=\"BACKGROUND\",status=\"ACTIVE\"}",
       "legendFormat": "active_background_session"
      },
      {
       "expr": "oracledb_session_total_sessions{instance=\"$host\",session_type=\"BACKGROUND\",status=\"InACTIVE\"}",
       "legendFormat": "inactive_background_session"
      }
     ]
    },
    {
     "title": "the amount of data",
     "type": "singlestat",
     "description": "Views for the amount of database's data,through computer all tablespaces usage,Include system、sysaux and undo.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(oracledb_tablespaces_total_size_bytes{instance=\"$host\"}-oracledb_tablespaces_free_bytes{instance=\"$host\"})/1024/1024/1024"
      }
     ]
    },
    {
     "title": "data diskgroup usage",
     "type": "singlestat",
     "description": "Views for db Asm Data  Diskgroup Usage",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(oracledb_asm_diskgroup_asm_space_total{instance=\"$host\",name=\"DATA\"}-oracledb_asm_diskgroup_asm_space_free{instance=\"$host\",name=\"DATA\"})*100/\noracledb_asm_diskgroup_asm_space_total{instance=\"$host\",name=\"DATA\"} ",
       "legendFormat": "asm diskgroup Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Efficiency Percentages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "buffer cache hit ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Buffer Cache Hit Ratio",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "oracledb_Cache_db_cache_ratio{instance=\"$host\",metric_name=\"Buffer Cache Hit Ratio\"} ",
       "legendFormat": "Buffer Cache Hit Ratio"
      }
     ]
    },
    {
     "title": "library cache hit ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Library Cache Hit Ratio",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "targets": [
      {
       "expr": "oracledb_Cache_db_cache_ratio{instance=\"$host\",metric_name=\"Library Cache Hit Ratio\"} ",
       "legendFormat": "Library Cache Hit Ratio"
      }
     ]
    },
    {
     "title": "row cache hit ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Row Cache Hit Ratio",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "oracledb_Cache_db_cache_ratio{instance=\"$host\",metric_name=\"Row Cache Hit Ratio\"}",
       "legendFormat": "Row Cache Hit Ratio"
      }
     ]
    },
    {
     "title": "cursor cache hit ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Cursor Cache Hit Ratio",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "targets": [
      {
       "expr": "oracledb_Cache_db_cache_ratio{instance=\"$host\",metric_name=\"Cursor Cache Hit Ratio\"} ",
       "legendFormat": "Cursor Cache Hit Ratio"
      }
     ]
    },
    {
     "title": "soft parse ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db soft  parse ratio",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "oracledb_sysmetrics_ratio_sysstat{instance=\"$host\",type=\"soft\"}*100",
       "legendFormat": "Soft Parse Ratio"
      }
     ]
    },
    {
     "title": "In-memory sort ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db In-memory sort ratio",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "oracledb_sysmetrics_ratio_sysstat{instance=\"$host\",type=\"sort\"}*100",
       "legendFormat": "In-memory sort ratio"
      }
     ]
    },
    {
     "title": "parse to execute ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Parse to execute ratio",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "oracledb_sysmetrics_ratio_sysstat{instance=\"$host\",type=\"parse_exec\"}*100",
       "legendFormat": "Parse to execute ratio"
      }
     ]
    },
    {
     "title": "Parse CPU to total CPU ratio",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Parse CPU to total CPU ratio",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "expr": "oracledb_sysmetrics_ratio_sysstat{instance=\"$host\",type=\"parse_cpu\"}*100",
       "legendFormat": "Parse CPU to total CPU ratio"
      }
     ]
    },
    {
     "title": "Parse time CPU to parse time elapsed",
     "type": "michaeldmoore-annunciator-panel",
     "description": "Views for db Parse time CPU to parse time elapsed",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "oracledb_sysmetrics_ratio_sysstat{instance=\"$host\",type=\"cpu_parse_elaps\"}*100",
       "legendFormat": "Parse time CPU to parse time elapsed"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Loads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Loads",
     "type": "graph",
     "description": "Views for database top activity(active session counts) with last 1 hour(group by wait_class)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_dbash_db_ash_cpu{instance=\"$host\"}",
       "legendFormat": "ON CPU"
      },
      {
       "expr": "oracledb_dbash_db_ash_background_cpu{instance=\"$host\"}",
       "legendFormat": "Background CPU"
      },
      {
       "expr": "oracledb_dbash_db_ash_queueing{instance=\"$host\"}",
       "legendFormat": "Queueing"
      },
      {
       "expr": "oracledb_dbash_db_ash_cluster{instance=\"$host\"}",
       "legendFormat": "Cluster"
      },
      {
       "expr": "oracledb_dbash_db_ash_administrative{instance=\"$host\"}",
       "legendFormat": "Administrative"
      },
      {
       "expr": "oracledb_dbash_db_ash_user_io{instance=\"$host\"}",
       "legendFormat": "User I/O"
      },
      {
       "expr": "oracledb_dbash_db_ash_system_io{instance=\"$host\"}",
       "legendFormat": "System I/O"
      },
      {
       "expr": "oracledb_dbash_db_ash_configuration{instance=\"$host\"}",
       "legendFormat": "Configuration"
      },
      {
       "expr": "oracledb_dbash_db_ash_commit{instance=\"$host\"}",
       "legendFormat": "Commit"
      },
      {
       "expr": "oracledb_dbash_db_ash_concurrency{instance=\"$host\"}",
       "legendFormat": "Concurrency"
      },
      {
       "expr": "oracledb_dbash_db_ash_scheduler{instance=\"$host\"}",
       "legendFormat": "Scheduler"
      },
      {
       "expr": "oracledb_dbash_db_ash_network{instance=\"$host\"}",
       "legendFormat": "Network"
      },
      {
       "expr": "oracledb_dbash_db_ash_application{instance=\"$host\"}",
       "legendFormat": "Application"
      },
      {
       "expr": "oracledb_dbash_db_ash_other{instance=\"$host\"}",
       "legendFormat": "Other"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O 吞吐",
     "type": "graph",
     "description": "Views for db  physical I/O througnput",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"Physical Read Total Bytes Per Sec\"}/1024/1024",
       "legendFormat": "Physical Read Per Sec"
      },
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"Physical Write Total Bytes Per Sec\"}/1024/1024",
       "legendFormat": "Physical Write Per Sec"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "description": "Views for db physical  read or write IOPS",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"Physical Read Total IO Requests Per Sec\"}",
       "legendFormat": "IOPS  Reads"
      },
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"Physical Write Total IO Requests Per Sec\"}",
       "legendFormat": "IOPS Writes"
      }
     ]
    },
    {
     "title": "user commits or rollbacks per sec",
     "type": "graph",
     "description": "Views for db user commits or rollbacks per seconds",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"User Commits Per Sec\"} ",
       "legendFormat": "User Commits Per Sec"
      },
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"User Rollbacks Per Sec\"}",
       "legendFormat": "User Rollbacks Per Sec"
      }
     ]
    },
    {
     "title": "Parse Count Per Sec",
     "type": "graph",
     "description": "Views for db Total Or Hard Parse Count Per Sec",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"Total Parse Count Per Sec\"} ",
       "legendFormat": "Total Parse Count Per Sec"
      },
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"Hard Parse Count Per Sec\"} ",
       "legendFormat": "Hard Parse Count Per Sec"
      }
     ]
    },
    {
     "title": "DB Blocks Per Sec",
     "type": "graph",
     "description": "Views for db  Block Received Per Second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"GC CR Block Received Per Second\"}",
       "legendFormat": "GC CR Block Received Per Sec"
      },
      {
       "expr": "oracledb_sysmetrics_sysmetrics{instance=\"$host\",metric_name=\"GC Current Block Received Per Second\"} ",
       "legendFormat": "GC Current Block Received Per Second"
      },
      {
       "expr": "oracledb_Cache_db_cache_ratio{instance=\"$host\",metric_name=\"DB Block Changes Per Sec\"}",
       "legendFormat": "DB Block Changes Per Sec"
      }
     ]
    },
    {
     "title": "Redo Generated Per Sec",
     "type": "graph",
     "description": "Views for db Redo Generated Per Sec",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "oracledb_Cache_db_cache_ratio{instance=\"$host\",metric_name=\"Redo Generated Per Sec\"}/1024",
       "legendFormat": "Redo Generated Per Sec"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Views for db host CPU Usage",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100-(avg by(instance)(irate(node_cpu{instance=\"linux_node\",mode=\"idle\"}[5m]))*100)",
       "legendFormat": "CPU_Usage"
      }
     ]
    },
    {
     "title": "Memory Usgae",
     "type": "graph",
     "description": "Views for db host Memory Usage",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100-((node_memory_MemFree{instance=\"linux_node\"}+node_memory_Cached{instance=\"linux_node\"}+node_memory_Buffers{instance=\"linux_node\"})/node_memory_MemTotal)*100",
       "legendFormat": "Memory Usage"
      }
     ]
    },
    {
     "title": "Disk Read Respond Time",
     "type": "graph",
     "description": "asm disk io read respond time  with last 5 minute",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(irate(node_disk_read_time_ms{instance=\"linux_node\",device=\"sdb\"}[5m]))",
       "legendFormat": "asmdisk_sdb"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_read_time_ms{instance=\"linux_node\",device=\"sdc\"}[5m]))",
       "legendFormat": "asmdisk_sdc"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_read_time_ms{instance=\"linux_node\",device=\"sdd\"}[5m]))",
       "legendFormat": "asmdisk_sdd"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_read_time_ms{instance=\"linux_node\",device=\"sde\"}[5m]))",
       "legendFormat": "asmdisk_sde"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_read_time_ms{instance=\"linux_node\",device=\"sdf\"}[5m]))",
       "legendFormat": "asmdisk_sdf"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_read_time_ms{instance=\"linux_node\",device=\"sdg\"}[5m]))",
       "legendFormat": "asmdisk_sdg"
      }
     ]
    },
    {
     "title": "Disk Write Respond Time",
     "type": "graph",
     "description": "asm disk io wait time  with last 5 miniter",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(irate(node_disk_write_time_ms{instance=\"linux_node\",device=\"sdb\"}[5m]))",
       "legendFormat": "asmdisk_sdb"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_write_time_ms{instance=\"linux_node\",device=\"sdc\"}[5m]))",
       "legendFormat": "asmdisk_sdc"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_write_time_ms{instance=\"linux_node\",device=\"sdd\"}[5m]))",
       "legendFormat": "asmdisk_sdd"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_write_time_ms{instance=\"linux_node\",device=\"sde\"}[5m]))",
       "legendFormat": "asmdisk_sde"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_write_time_ms{instance=\"linux_node\",device=\"sdf\"}[5m]))",
       "legendFormat": "asmdisk_sdf"
      },
      {
       "expr": "sum by(instance)(irate(node_disk_write_time_ms{instance=\"linux_node\",device=\"sdg\"}[5m]))",
       "legendFormat": "asmdisk_sdg"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "description": "Views for db host network I/O(receive bytes and transmit bytes)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance)(irate(node_network_receive_bytes{instance=\"linux_node\",device!~\"bond.*?|lo\"}[5m])/128)",
       "legendFormat": "Up_Network_IO"
      },
      {
       "expr": "sum by(instance)(irate(node_network_transmit_bytes{instance=\"linux_node\",device!~\"bond.*?|lo\"}[5m])/128)",
       "legendFormat": "Down_Network_IO"
      }
     ]
    },
    {
     "title": "Host Avg Load",
     "type": "graph",
     "description": "host load information with last 1 minute",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=\"linux_node\"}",
       "legendFormat": "host_avg_load1"
      }
     ]
    }
   ]
  }
 ]
}