{
 "title": "Presto Exporter",
 "description": "for: https://github.com/yahoojapan/presto_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "分组名称", "query": "label_values(up,job)" },
   {
    "name": "node",
    "label": "机器",
    "query": "label_values(up{job=\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Worker Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "presto_cluster_active_workers{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_running_queries{instance=~\"$node\"}",
     "legendFormat": "running_queries"
    },
    {
     "expr": "presto_cluster_queued_queries{instance=~\"$node\"}",
     "legendFormat": "queued_queries"
    },
    {
     "expr": "presto_cluster_blocked_queries{instance=~\"$node\"}",
     "legendFormat": "blocked_queries"
    }
   ]
  },
  {
   "title": "running_drivers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "presto_cluster_running_drivers", "legendFormat": "running_drivers" }
   ]
  },
  {
   "title": "total_input_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_total_input_bytes{instance=~\"$node\"}",
     "legendFormat": "total_input_bytes"
    }
   ]
  },
  {
   "title": "total_input_rows",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_total_input_rows{instance=~\"$node\"}",
     "legendFormat": "total_input_rows"
    }
   ]
  },
  {
   "title": "total_cpu_time_secs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_total_cpu_time_secs{instance=~\"$node\"}",
     "legendFormat": "total_cpu_time_secs"
    }
   ]
  },
  {
   "title": "reserved_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_reserved_memory{instance=~\"$node\"}",
     "legendFormat": "reserved_memory"
    }
   ]
  }
 ]
}